using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;

public static class Constants
{
    public static List<int> EASY_SCORE_ARRAY = new List<int> { 0, 0, 1, 2, 3 };

    public static List<int> HARD_SCORE_ARRAY = new List<int> { -3, -2, -1, 1, 2, 3 };

    public static List<Card> Cards = new List<Card>
    {
        new Card(JokeTypesEnum.DadJokes, "I’m scared for the calendar, its days are numbered."),
        new Card(JokeTypesEnum.DadJokes, "What do you call a factory that makes average products? A satisfactory"),
        new Card(JokeTypesEnum.DadJokes, "How much does a polar bear weigh? Enough to BREAK THE ICE!"),
        new Card(JokeTypesEnum.CountryJokes, "What's the best thing about Switzerland? I don't know, but the flag is a big plus."),
        new Card(JokeTypesEnum.CountryJokes, "I only have one shoe tied… why’s that? Well it’s because the label says TAIWAN!"),
        new Card(JokeTypesEnum.CountryJokes, "My friend likes Patrick likes to party, I always say “It’s time to break it DownPatrick!"),
        new Card(JokeTypesEnum.ReligiousJokes, "God made humanity… took one look and said “What a mistake”"),
        new Card(JokeTypesEnum.ProgrammerJokes, "Let’s JAVA good time"),
        new Card(JokeTypesEnum.ProgrammerJokes, "My eyesight is top tier, because I can C#"),
        new Card(JokeTypesEnum.ProgrammerJokes, "Game Jams always promote UNITY"),
        new Card(JokeTypesEnum.WittyJokes, "What did the Christmas Cracker say to the Fortune Cookie? Man you've got fortunes and well wishes, I've just got sh*%&y jokes"),
        new Card(JokeTypesEnum.WittyJokes, "Santa lost a bet to the mafia... the mob boss said 'YULE be sorry if ya don't pay up' "),
        new Card(JokeTypesEnum.WittyJokes, "My son is dyslexic, he wrote his Christmas list for SATAN "),
        new Card(JokeTypesEnum.CountryJokes, "Where do beans go on holiday?  The Carib-bean"),
        new Card(JokeTypesEnum.DadJokes, "What do you call a retired vegetable?  A has-bean."),
        new Card(JokeTypesEnum.WittyJokes, "What kind of show do green bean plants record?  Pod casts"),
        new Card(JokeTypesEnum.WittyJokes, "What type of bean is the fastest?  The runner bean"),
        new Card(JokeTypesEnum.DadJokes, "What kind of vegetable can tie your shoelaces?  String beans."),
        new Card(JokeTypesEnum.WittyJokes, "Why did the bean sell his car?  The back seat didn't have enough legume!"),
        new Card(JokeTypesEnum.DadJokes, "What do you call a cat that likes to eat broad beans?  Puss 'n' Toots."),
        new Card(JokeTypesEnum.DadJokes, "Why did the bean get promoted?  Beacause it was outstanding in its field!"),
        new Card(JokeTypesEnum.CountryJokes, "What movie do beans love the most?  Pirates of the Carib-bean"),
        new Card(JokeTypesEnum.WittyJokes, "What do you get when you mix onions and beans?  Tear gas!"),
        new Card(JokeTypesEnum.DadJokes, "What's a werewolf's favourite bean to eat?  Human beans!"),
        new Card(JokeTypesEnum.WittyJokes, "Why should you invest in the bean market?  Because the stalks can only go up!"),
        new Card(JokeTypesEnum.DadJokes, "Why was the bean always so cold?  It was just chilli!"),
        new Card(JokeTypesEnum.DadJokes, "How do baked beans learn from their mistakes?  They use Heinz sight!"),
        new Card(JokeTypesEnum.WittyJokes, "Why did the bean blush?  Because it saw the salad dressing!"),
        new Card(JokeTypesEnum.DadJokes, "What do you get get when you cross a cow with a coffee bean?  De-calf."),
        new Card(JokeTypesEnum.DadJokes, "What happens to coffee beans when they have a similar experience?  They get deja-brew!"),
        new Card(JokeTypesEnum.DadJokes, "What did the coffee bean say when it won a talent competition?  I really espresso-ed myself"),
        new Card(JokeTypesEnum.DadJokes, "How are coffee beans like teenagers?  They both keep getting grounded"),
        new Card(JokeTypesEnum.WittyJokes, "Did you hear about the bean that changed career?  SHe went into a different field"),
        new Card(JokeTypesEnum.WittyJokes, "I've been told green beans are good for you...but why are they better than the other jelly bean colours?"),
        new Card(JokeTypesEnum.ProgrammerJokes, "99 little bugs in the code, 99 little bug.  You take one down, patch it around, 125 little bugs in the code"),
        new Card(JokeTypesEnum.ProgrammerJokes, "There are 10 kinds of people in the world, those who understand binary and those who don't"),
        new Card(JokeTypesEnum.ProgrammerJokes, "There are 2 types of people in the world, those who can extrapolate from incomplete data"),
        new Card(JokeTypesEnum.ProgrammerJokes, "Programming is 10% writing code and 90%  understanding why it's not working"),
        new Card(JokeTypesEnum.ProgrammerJokes, "Why did the programmer quit her job?  Because she didn't get arrays"),
        new Card(JokeTypesEnum.ProgrammerJokes, "Why do programmers prefer dark mode?  Beacuse light attracts bugs"),
        new Card(JokeTypesEnum.ProgrammerJokes, "Programmer: An organism that turns coffee into software"),
        new Card(JokeTypesEnum.WittyJokes, "Why can't you trust an atom?  Because they make up everything!"),
        new Card(JokeTypesEnum.ProgrammerJokes, "There's no place like 127.0.0.1"),
        new Card(JokeTypesEnum.ProgrammerJokes, "If at first you don't succeed, call it version 1.0"),
        new Card(JokeTypesEnum.ProgrammerJokes, "What is the most used language in programming?  Profanity"),
        new Card(JokeTypesEnum.ProgrammerJokes, "My mind is like an internet browser...19 tabs open, 3 of them are frozen, ads popping up everywhere, and I have no idea where the music is coming from"),
        new Card(JokeTypesEnum.ProgrammerJokes, "Algorithm: words used by programmers when they don't want to explain what they did"),
        new Card(JokeTypesEnum.ProgrammerJokes, "When in doubt, // it out"),
        new Card(JokeTypesEnum.ProgrammerJokes, "What do cats & programmers have in common?  When either one is excited, it's because they found a bug"),
        new Card(JokeTypesEnum.ProgrammerJokes, "Hip, hip, array!"),
        new Card(JokeTypesEnum.ProgrammerJokes, "Programmer: a person who fixed a program you didn't know you had in a way you don't understand"),
        new Card(JokeTypesEnum.ProgrammerJokes, "A good programmer is someone who looks both ways before crossing a one-way street"),
        new Card(JokeTypesEnum.ProgrammerJokes, "A user interface is like a joke...if you have to explain it, it's not good"),
        new Card(JokeTypesEnum.ProgrammerJokes, "Software can be fast, reliable, and cheap - choose any two"),
        new Card(JokeTypesEnum.ProgrammerJokes, "Why did the developer use a credit card at the shop?  Because he had cleared all his cache"),
        new Card(JokeTypesEnum.CountryJokes, "England doesn't have a kidney bank, but it does have a Liverpool"),
        new Card(JokeTypesEnum.CountryJokes, "Why do the French eat snails?  They don't like fast food"),
        new Card(JokeTypesEnum.CountryJokes, "England doesn't have a kidney bank, but it does have a Liverpool"),
        new Card(JokeTypesEnum.CountryJokes, "A slice of dessert is $2.50 in Jamaica and £3.00 in the Bahamas.  These are the pi rates of the Carribean"),
        new Card(JokeTypesEnum.CountryJokes, "What do you call a vegan Viking?  A Norvegan!"),
        new Card(JokeTypesEnum.CountryJokes, "Which country's capital is growing the fastest?  Ireland - every day it's Dublin!"),
        new Card(JokeTypesEnum.CountryJokes, "Want to hear a Swedish joke?  Never mind, there's Norway I could Finnish it!"),
        new Card(JokeTypesEnum.CountryJokes, "I'm Hungary..what's for dinner?"),
        new Card(JokeTypesEnum.CountryJokes, "What do you call an insect that lives in America?  A USB"),
        new Card(JokeTypesEnum.CountryJokes, "What does the Loch Ness monster eat?  Fish and ships"),
        new Card(JokeTypesEnum.CountryJokes, "What do frogs eat in Paris?  French flies"),
        new Card(JokeTypesEnum.WittyJokes, "Waiter waiter, do you have frogs' leags?  No sir, I always walk like this"),
        new Card(JokeTypesEnum.WittyJokes, "Waiter waiter, there's a fly in my soup!  Keep your voice down sir, or everybody will want one"),
        new Card(JokeTypesEnum.DadJokes, "'Nighty night' 'Pyjama pyjama' "),
        new Card(JokeTypesEnum.CountryJokes, "I have a Russian friend who's a sound technician.  And a Czech one too...a Czech one too"),
        new Card(JokeTypesEnum.CountryJokes, "What kind of birds can you find in Portugal?  Portugeese"),
        new Card(JokeTypesEnum.CountryJokes, "What is the most common scam in Egypt?  Pyramid schemes"),
        new Card(JokeTypesEnum.CountryJokes, "What was the most popular kids' movie in Ancient Greece?  Troy story"),
        new Card(JokeTypesEnum.ReligiousJokes, "What did the man say to the Rabbi?  Hee Broo"),
        new Card(JokeTypesEnum.CountryJokes, "Did you hear about the Italian chef that died?  He pasta way"),
        new Card(JokeTypesEnum.CountryJokes, "In what country is Prague located?  Hold on let me Czech"),
        new Card(JokeTypesEnum.CountryJokes, "In Prague, is hide and seek known as caching Czechs?"),
        new Card(JokeTypesEnum.CountryJokes, "Why do pipers walk while they play?  To escape the noise"),
        new Card(JokeTypesEnum.CountryJokes, "Why do all Swedish military ships have QR codes on them?  So when they enter port, they can just Scan da navy in!"),
        new Card(JokeTypesEnum.CountryJokes, "How was copper wire invented?  Two Scotsmen fighting over a penny"),
        new Card(JokeTypesEnum.CountryJokes, "What pan is the best to make sushi in?  Japan"),
        new Card(JokeTypesEnum.CountryJokes, "Why is it hard to make friends in Antarctica?  Because you can't break the ice"),
        new Card(JokeTypesEnum.CountryJokes, "What do you call bullies from Malta?  Mal-teasers"),
        new Card(JokeTypesEnum.CountryJokes, "Since my girlfriend moved to Siberia, our relationship hasn't been the same...she is so cold and distant"),
        new Card(JokeTypesEnum.CountryJokes, "The Sahara desert drifts into a bar and the bartender says 'long time no sea' "),
        new Card(JokeTypesEnum.CountryJokes, "I've heard that Argentina is starting to get a little colder.  In fact, it's bordering on Chile"),
        new Card(JokeTypesEnum.CountryJokes, "I've heard that Germans are panic buying sausages and cheese...it's the Wurst Käse scenario "),
        new Card(JokeTypesEnum.CountryJokes, "What's Santa's nationality?  North Polish "),
        new Card(JokeTypesEnum.CountryJokes, "What genre are national anthems?  Country "),
        new Card(JokeTypesEnum.CountryJokes, "What did the Icelandic dog say?  Bjork Bjork "),
        new Card(JokeTypesEnum.ReligiousJokes, "Why did the Dalai Lama go to Las Vegas?  Because he loves Tibet "),
        new Card(JokeTypesEnum.CountryJokes, "What hapens when the smog lifts over Southern California?  U.C.L.A "),
        new Card(JokeTypesEnum.CountryJokes, "What kind of car does an Icelandic person drive?  A Fjord "),
        new Card(JokeTypesEnum.CountryJokes, "What do you call your angry Parisian relative?  A crossaunt "),
        new Card(JokeTypesEnum.CountryJokes, "Someone beat me up with a map of Belgium...now I'm covered in Bruges "),
        new Card(JokeTypesEnum.CountryJokes, "What is the cookie capital of Brazil?  Oreo di Janiero "),
        new Card(JokeTypesEnum.CountryJokes, "What blood type do people from Taiwan have?  Taipei "),
        new Card(JokeTypesEnum.ReligiousJokes, "What are athiests called in India?  Naan believers "),
        new Card(JokeTypesEnum.CountryJokes, "My parents were on a Mediterranean cruise.  When I arrived unannounced, I Cyprus-ed them "),
        new Card(JokeTypesEnum.CountryJokes, "What's a German's favourite number?  Nein "),
        new Card(JokeTypesEnum.CountryJokes, "How was airport security in Los Angeles?  Quite LAX "),
        new Card(JokeTypesEnum.ReligiousJokes, "Which Bible character was super fit?  ABSalom "),
        new Card(JokeTypesEnum.ReligiousJokes, "What did Adam say when his wife asked his favourite holiday?  'It's Christmas, Eve' "),
        new Card(JokeTypesEnum.ReligiousJokes, "What did pirates call Noah's boat?  'The arrrrrrrk' "),
        new Card(JokeTypesEnum.ReligiousJokes, "Why did Boaz hate lying?  Beacuse he loved tRUTH "),
        new Card(JokeTypesEnum.ReligiousJokes, "Why didn't anyone want to fight Goliath?  It seemed like a GIANT ordeal "),
        new Card(JokeTypesEnum.ReligiousJokes, "How do you know atoms are Catholic?  Because they have mass "),
        new Card(JokeTypesEnum.ReligiousJokes, "Who in the Bible knew the most people?  Abraham - he knew a Lot "),
        new Card(JokeTypesEnum.ReligiousJokes, "Which Bible character was the best entertainer?  Samson - he brought the house down "),
        new Card(JokeTypesEnum.ReligiousJokes, "Who in the Bible were the greatest businessmen?  The prophets "),
        new Card(JokeTypesEnum.ReligiousJokes, "When someone needed a boat built, what did the people in town say?  'We Noah guy' "),
        new Card(JokeTypesEnum.WittyJokes, "What did the grape say when it got stepped on?  Nothing, it just let out a little Wine "),
        new Card(JokeTypesEnum.ReligiousJokes, "What size of planks were used to build the ark?  2 x 2 "),
        new Card(JokeTypesEnum.ReligiousJokes, "I got divorced for religious reasons. My husband thought he was God; I disagreed "),
        new Card(JokeTypesEnum.ReligiousJokes, "What's the best way to contact God?  Knee-mail  "),
        new Card(JokeTypesEnum.WittyJokes, "Dr Bean lost all his patients...he couldn't find a pulse"),
        new Card(JokeTypesEnum.DadJokes, "What do cats eat on a hot day?  A mice-cream cone"),
        new Card(JokeTypesEnum.WittyJokes, "How do cats always get their way?  They are very purrsuasive"),
        new Card(JokeTypesEnum.WittyJokes, "What's a cat's favourite film?  The Sound of Mewsic"),
        new Card(JokeTypesEnum.WittyJokes, "What's a cat's favourite magazine?  Good Mousekeeping"),
        new Card(JokeTypesEnum.WittyJokes, "What's a cat's favourite colour?  Purrple"),
        new Card(JokeTypesEnum.WittyJokes, "Why was a cat afraid of the tree?  Because of its bark"),
        new Card(JokeTypesEnum.WittyJokes, "What did the confused cat say?  'I'm purrplexed' "),
        new Card(JokeTypesEnum.WittyJokes, "What do you call a cat who loves bowling?  An alley cat"),
        new Card(JokeTypesEnum.DadJokes, "What do cats love to do in the morning?  Read the mewspaper "),
        new Card(JokeTypesEnum.WittyJokes, "What is a cat's favourite type of theatre show?  Mewsicals "),
        new Card(JokeTypesEnum.WittyJokes, "What do cats use to make coffee?  A purr-colator "),
        new Card(JokeTypesEnum.WittyJokes, "How does a feline like to shop?  It looks through a CATalogue "),
        new Card(JokeTypesEnum.WittyJokes, "What type of feline works for the Red Cross?  A first aid kit "),
        new Card(JokeTypesEnum.WittyJokes, "What do you call a pile of kittens?  A meowntain "),
        new Card(JokeTypesEnum.DadJokes, "What do cats like best for breakfast?  Mice Krispies "),
        new Card(JokeTypesEnum.WittyJokes, "What's a kitten's favourite school subject?  Hiss-tory "),
        new Card(JokeTypesEnum.WittyJokes, "What's a cat's favourite TV show?  Claw and order "),
        new Card(JokeTypesEnum.WittyJokes, "How did the cat know she was pregnant?  The vet told her the test was pawsitive "),
        new Card(JokeTypesEnum.WittyJokes, "How did the cat lose all its money?  It got caught in a purramid scheme "),
        new Card(JokeTypesEnum.DadJokes, "What did the cat say when it ran out of treats?  'It's a CATastrophe' "),
        new Card(JokeTypesEnum.DadJokes, "What animal should you never play cards with?  A cheetah "),
        new Card(JokeTypesEnum.WittyJokes, "Why did the cat get fired from its IT job?  It kept getting distracted by the mouse "),
        new Card(JokeTypesEnum.WittyJokes, "What is a cat's favourite day?  Caturday "),
        new Card(JokeTypesEnum.WittyJokes, "Why did the cat never get hired as a DJ?  He always pawsed the tunes "),
        new Card(JokeTypesEnum.WittyJokes, "Where do feline families go for day trips?  The mewseum "),
        new Card(JokeTypesEnum.WittyJokes, "What's smarter than a talking cat?  A spelling bee "),
        new Card(JokeTypesEnum.WittyJokes, "What's a cat's favourite song?  Three blind mice "),
        new Card(JokeTypesEnum.WittyJokes, "What cat likes living in water?  An octo-puss "),
        new Card(JokeTypesEnum.WittyJokes, "What do cats wear to bed?  Paw-jamas "),
        new Card(JokeTypesEnum.WittyJokes, "Why are cats terrible storytellers?  Bceause they only have one tail "),
        new Card(JokeTypesEnum.WittyJokes, "What happened when the cat ate a clown fish?  It felt funny"),
        new Card(JokeTypesEnum.WittyJokes, "When is it bad luck to see a black cat?  When you are a mouse "),
        new Card(JokeTypesEnum.DadJokes, "What cat works at Christmas?  Santa Claws "),
        new Card(JokeTypesEnum.WittyJokes, "What do you get if you cross a tiger and a sheep?  A stripy jumper "),
        new Card(JokeTypesEnum.WittyJokes, "What does a cat drive?  A Furrari "),
        new Card(JokeTypesEnum.CountryJokes, "Where does a cat like to go on holiday?  The Canary Islands "),
        new Card(JokeTypesEnum.CountryJokes, "What is a cat's favourote city?  HAmsterdam "),
        new Card(JokeTypesEnum.WittyJokes, "If the Earth was flat, cats would push everything off it "),
        new Card(JokeTypesEnum.WittyJokes, "Dogs have owners...cats have staff "),
        new Card(JokeTypesEnum.WittyJokes, "Dogs can't operate MRI scanners, but CATscan "),
        new Card(JokeTypesEnum.CountryJokes, "In Ancient Egypt, cats were worshipped as gods...they have never forgotten this "),
        new Card(JokeTypesEnum.DadJokes, "I will rise, but I won't shine "),
        new Card(JokeTypesEnum.WittyJokes, "What did one flea say to the other?  'Shall we walk or take the cat?' "),
        new Card(JokeTypesEnum.DadJokes, "What's the difference between a teenager and a cat?  One is lazy, eats a lot & doesn't care who brings the food.  The other is an animal "),
        new Card(JokeTypesEnum.DadJokes, "What does a baby computer call his father?  DaTa"),
        new Card(JokeTypesEnum.DadJokes, "I only get sick on weekdays - I must have a weekend immune system"),
        new Card(JokeTypesEnum.CountryJokes, "What do you call a Frenchman in sandals?  Philippe Flop"),
        new Card(JokeTypesEnum.DadJokes, "Why is it so cheap to host a party at a haunted house?  Because the ghosts bring all the boos"),
        new Card(JokeTypesEnum.DadJokes, "I just found out I'm colourblind...the news came out of the purple!"),
        new Card(JokeTypesEnum.DadJokes, "How do cows stay up to date?  They read the moospaper!"),
    };

}